POST http://localhost:3001/app/addRole
Content-Type: application/json

{
    "name":"Shift Manager"
}

###

POST http://localhost:3001/app/addUser
Content-Type: application/json

{
    "fullName":"כוכבה",
    "username":"שביט",
    "password":"nba",
    "role":"cleaner"
}