POST http://localhost:3001/app
Content-Type: application/json

{
    "name":"devolper"
}

###

POST http://localhost:3001/app/addUser
Content-Type: application/json

{
    "fullName":"nba",
    "username":"ofek1",
    "password":"nba",
    "role":"649851fdf84cbd0787d4c020"
}