POST http://localhost:3001/app/addDay
Content-Type: application/json

{
    "name":"בדיקה בדיקה בדיקה",
    "shifts": []
}

###
GET http://localhost:3001/app/getDays
Content-Type: application/json 


###
PUT http://localhost:3001/app/updateShiftsOfWeek
Content-Type: application/json 

{
    "weekId": "64e12d504c8766dd86034012",
    "object":{"shifts":[{"_id":"64e1f808ead63b98fcf6fcfd","workers":[],"availableWorkers":[]},{"_id":"64e1f80aead63b98fcf6fd09","workers":["123456789012"],"availableWorkers":[]},{"_id":"64e1f80cead63b98fcf6fd16","workers":[],"availableWorkers":[]},{"_id":"64e1f80dead63b98fcf6fd24","workers": [],"availableWorkers": []},{"_id":"64e1f80eead63b98fcf6fd33","workers":[],"availableWorkers":[]},{"_id":"64e1f810ead63b98fcf6fd43","workers":[],"availableWorkers":[]},{"_id":"64e1f811ead63b98fcf6fd54","workers":[],"availableWorkers":[]},{"_id":"64e1f812ead63b98fcf6fd67","workers":[],"availableWorkers":[]}]}}
###
GET http://localhost:3001/app/getDay/649b33527747ae58985fde2f
Content-Type: application/json 

###

DELETE  http://localhost:3001/app/deleteDay/649ebf8086d5ecb147f51df2
Content-Type: application/json 

###
PUT http://localhost:3001/app/editDay
Content-Type: application/json

{
    "_id": "649b3c2e18f3287977da1009",
    "name": "ראשון",
    "shifts": []
}